<?php

use Illuminate\Database\Seeder;

class WeaponsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('m_weapons')->delete();
        $data = [
            [
                'id' => 1,
                'name' => 'スプラシューター',
                'image_url' => '/weapon/1.png',
                'category_id' => 1,
                "sub_id" => 7,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 2,
                'name' => 'スプラシューターコラボ',
                'image_url' => '/weapon/2.png',
                'category_id' => 1,
                "sub_id" => 1,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 3,
                'name' => 'ヒーローシューターレプリカ',
                'image_url' => '/weapon/3.png',
                'category_id' => 1,
                "sub_id" => 7,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 4,
                'name' => 'オクタシューターレプリカ',
                'image_url' => '/weapon/4.png',
                'category_id' => 1,
                "sub_id" => 1,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 5,
                'name' => 'スプラシューターベッチュー',
                'image_url' => '/weapon/5.png',
                'category_id' => 1,
                "sub_id" => 6,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 6,
                'name' => 'プライムシューター',
                'image_url' => '/weapon/6.png',
                'category_id' => 1,
                "sub_id" => 2,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 7,
                'name' => 'プライムシューターコラボ',
                'image_url' => '/weapon/7.png',
                'category_id' => 1,
                "sub_id" => 6,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 8,
                'name' => 'プライムシューターベッチュー',
                'image_url' => '/weapon/8.png',
                'category_id' => 1,
                "sub_id" => 1,
                "special_id" => 12,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 9,
                'name' => 'シャープマーカー',
                'image_url' => '/weapon/9.png',
                'category_id' => 1,
                "sub_id" => 4,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 10,
                'name' => 'シャープマーカーネオ',
                'image_url' => '/weapon/10.png',
                'category_id' => 1,
                "sub_id" => 7,
                "special_id" => 7,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 11,
                'name' => 'わかばシューター',
                'image_url' => '/weapon/11.png',
                'category_id' => 1,
                "sub_id" => 1,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 12,
                'name' => 'もみじシューター',
                'image_url' => '/weapon/12.png',
                'category_id' => 1,
                "sub_id" => 5,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],     
            [
                'id' => 13,
                'name' => 'おちばシューター',
                'image_url' => '/weapon/13.png',
                'category_id' => 1,
                "sub_id" => 11,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],   
            [
                'id' => 14,
                'name' => 'プロモデラーMG',
                'image_url' => '/weapon/14.png',
                'category_id' => 1,
                "sub_id" => 6,
                "special_id" => 10,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 15,
                'name' => 'プロモデラーRG',
                'image_url' => '/weapon/15.png',
                'category_id' => 1,
                "sub_id" => 10,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 16,
                'name' => 'プロモデラーPG',
                'image_url' => '/weapon/16.png',
                'category_id' => 1,
                "sub_id" => 7,
                "special_id" => 12,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 17,
                'name' => 'N-ZAP85',
                'image_url' => '/weapon/17.png',
                'category_id' => 1,
                "sub_id" => 6,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 18,
                'name' => 'N-ZAP89',
                'image_url' => '/weapon/18.png',
                'category_id' => 1,
                "sub_id" => 5,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 19,
                'name' => 'N-ZAP83',
                'image_url' => '/weapon/19.png',
                'category_id' => 1,
                "sub_id" => 10,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 20,
                'name' => '.52ガロン',
                'image_url' => '/weapon/20.png',
                'category_id' => 1,
                "sub_id" => 2,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 21,
                'name' => '.52ガロンデコ',
                'image_url' => '/weapon/21.png',
                'category_id' => 1,
                "sub_id" => 8,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 22,
                'name' => '.52ガロンベッチュー',
                'image_url' => '/weapon/22.png',
                'category_id' => 1,
                "sub_id" => 3,
                "special_id" => 12,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 23,
                'name' => 'ジェットスイーパー',
                'image_url' => '/weapon/23.png',
                'category_id' => 1,
                "sub_id" => 4,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 24,
                'name' => 'ジェットスイーパーカスタム',
                'image_url' => '/weapon/24.png',
                'category_id' => 1,
                "sub_id" => 7,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 25,
                'name' => 'L3リールガン',
                'image_url' => '/weapon/25.png',
                'category_id' => 1,
                "sub_id" => 8,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 26,
                'name' => 'L3リールガンD',
                'image_url' => '/weapon/26.png',
                'category_id' => 1,
                "sub_id" => 7,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 27,
                'name' => 'L3リールガンベッチュー',
                'image_url' => '/weapon/27.png',
                'category_id' => 1,
                "sub_id" => 3,
                "special_id" => 11,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 28,
                'name' => '.96ガロン',
                'image_url' => '/weapon/28.png',
                'category_id' => 1,
                "sub_id" => 10,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 29,
                'name' => '.96ガロンデコ',
                'image_url' => '/weapon/29.png',
                'category_id' => 1,
                "sub_id" => 3,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 30,
                'name' => 'H3リールガン',
                'image_url' => '/weapon/30.png',
                'category_id' => 1,
                "sub_id" => 2,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 31,
                'name' => 'H3リールガンD',
                'image_url' => '/weapon/31.png',
                'category_id' => 1,
                "sub_id" => 6,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 32,
                'name' => 'H3リールガンチェリー',
                'image_url' => '/weapon/32.png',
                'category_id' => 1,
                "sub_id" => 3,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 33,
                'name' => 'ボールドマーカー',
                'image_url' => '/weapon/33.png',
                'category_id' => 1,
                "sub_id" => 8,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 34,
                'name' => 'ボールドマーカーネオ',
                'image_url' => '/weapon/34.png',
                'category_id' => 1,
                "sub_id" => 9,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 35,
                'name' => 'ボールドマーカー7',
                'image_url' => '/weapon/35.png',
                'category_id' => 1,
                "sub_id" => 1,
                "special_id" => 11,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 36,
                'name' => 'ボトルガイザー',
                'image_url' => '/weapon/36.png',
                'category_id' => 1,
                "sub_id" => 3,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 37,
                'name' => 'ボトルガイザーフォイル',
                'image_url' => '/weapon/37.png',
                'category_id' => 1,
                "sub_id" => 1,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 38,
                'name' => 'ホットブラスター',
                'image_url' => '/weapon/38.png',
                'category_id' => 4,
                "sub_id" => 4,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 39,
                'name' => 'ホットブラスターカスタム',
                'image_url' => '/weapon/39.png',
                'category_id' => 4,
                "sub_id" => 5,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 40,
                'name' => 'ヒーローブラスターレプリカ',
                'image_url' => '/weapon/40.png',
                'category_id' => 4,
                "sub_id" => 4,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 41,
                'name' => 'ラピッドブラスター',
                'image_url' => '/weapon/41.png',
                'category_id' => 4,
                "sub_id" => 12,
                "special_id" => 15,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 42,
                'name' => 'ラピッドブラスターデコ',
                'image_url' => '/weapon/42.png',
                'category_id' => 4,
                "sub_id" => 6,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 43,
                'name' => 'ラピッドブラスターベッチュー',
                'image_url' => '/weapon/43.png',
                'category_id' => 4,
                "sub_id" => 11,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 44,
                'name' => 'ノヴァブラスター',
                'image_url' => '/weapon/44.png',
                'category_id' => 4,
                "sub_id" => 1,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 45,
                'name' => 'ノヴァブラスターネオ',
                'image_url' => '/weapon/45.png',
                'category_id' => 4,
                "sub_id" => 12,
                "special_id" => 7,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 46,
                'name' => 'ノヴァブラスターベッチュー',
                'image_url' => '/weapon/46.png',
                'category_id' => 4,
                "sub_id" => 13,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 47,
                'name' => 'クラッシュブラスター',
                'image_url' => '/weapon/47.png',
                'category_id' => 4,
                "sub_id" => 1,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 48,
                'name' => 'クラッシュブラスターネオ',
                'image_url' => '/weapon/48.png',
                'category_id' => 4,
                "sub_id" => 8,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 49,
                'name' => 'Rブラスターエリート',
                'image_url' => '/weapon/49.png',
                'category_id' => 4,
                "sub_id" => 4,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 50,
                'name' => 'Rブラスターエリートデコ',
                'image_url' => '/weapon/50.png',
                'category_id' => 4,
                "sub_id" => 3,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 51,
                'name' => 'ロングブラスター',
                'image_url' => '/weapon/51.png',
                'category_id' => 4,
                "sub_id" => 6,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 52,
                'name' => 'ロングブラスターカスタム',
                'image_url' => '/weapon/52.png',
                'category_id' => 4,
                "sub_id" => 8,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 53,
                'name' => 'ロングブラスターネクロ',
                'image_url' => '/weapon/53.png',
                'category_id' => 4,
                "sub_id" => 7,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 54,
                'name' => 'スプラローラー',
                'image_url' => '/weapon/54.png',
                'category_id' => 5,
                "sub_id" => 8,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 55,
                'name' => 'スプラローラーコラボ',
                'image_url' => '/weapon/55.png',
                'category_id' => 5,
                "sub_id" => 9,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 56,
                'name' => 'ヒーローローラーレプリカ',
                'image_url' => '/weapon/56.png',
                'category_id' => 5,
                "sub_id" => 8,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 57,
                'name' => 'スプラローラーベッチュー',
                'image_url' => '/weapon/57.png',
                'category_id' => 5,
                "sub_id" => 1,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 58,
                'name' => 'ダイナモローラー',
                'image_url' => '/weapon/58.png',
                'category_id' => 5,
                "sub_id" => 12,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 59,
                'name' => 'ダイナモローラーテスラ',
                'image_url' => '/weapon/59.png',
                'category_id' => 5,
                "sub_id" => 1,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 60,
                'name' => 'ダイナモローラーベッチュー',
                'image_url' => '/weapon/60.png',
                'category_id' => 5,
                "sub_id" => 10,
                "special_id" => 12,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 61,
                'name' => 'カーボンローラー',
                'image_url' => '/weapon/61.png',
                'category_id' => 5,
                "sub_id" => 5,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 62,
                'name' => 'カーボンローラーデコ',
                'image_url' => '/weapon/62.png',
                'category_id' => 5,
                "sub_id" => 7,
                "special_id" => 13,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 63,
                'name' => 'ヴァリアブルローラー',
                'image_url' => '/weapon/63.png',
                'category_id' => 5,
                "sub_id" => 3,
                "special_id" => 15,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 64,
                'name' => 'ヴァリアブルローラーフォイル',
                'image_url' => '/weapon/64.png',
                'category_id' => 5,
                "sub_id" => 6,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 65,
                'name' => 'ホクサイ',
                'image_url' => '/weapon/65.png',
                'category_id' => 6,
                "sub_id" => 5,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 66,
                'name' => 'ヒーローブラシレプリカ',
                'image_url' => '/weapon/66.png',
                'category_id' => 6,
                "sub_id" => 5,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 67,
                'name' => 'ホクサイ・ヒュー',
                'image_url' => '/weapon/67.png',
                'category_id' => 6,
                "sub_id" => 9,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 68,
                'name' => 'ホクサイベッチュー',
                'image_url' => '/weapon/68.png',
                'category_id' => 6,
                "sub_id" => 6,
                "special_id" => 11,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 69,
                'name' => 'パブロ',
                'image_url' => '/weapon/69.png',
                'category_id' => 6,
                "sub_id" => 1,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 70,
                'name' => 'パブロ・ヒュー',
                'image_url' => '/weapon/70.png',
                'category_id' => 6,
                "sub_id" => 12,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 71,
                'name' => 'パーマネント・パブロ',
                'image_url' => '/weapon/71.png',
                'category_id' => 6,
                "sub_id" => 10,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 72,
                'name' => 'スプラチャージャー',
                'image_url' => '/weapon/72.png',
                'category_id' => 3,
                "sub_id" => 1,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 73,
                'name' => 'スプラスコープ',
                'image_url' => '/weapon/73.png',
                'category_id' => 3,
                "sub_id" => 1,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 74,
                'name' => 'スプラチャージャーコラボ',
                'image_url' => '/weapon/74.png',
                'category_id' => 3,
                "sub_id" => 3,
                "special_id" => 7,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 75,
                'name' => 'スプラスコープコラボ',
                'image_url' => '/weapon/75.png',
                'category_id' => 3,
                "sub_id" => 3,
                "special_id" => 7,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 76,
                'name' => 'ヒーローチャージャーレプリカ',
                'image_url' => '/weapon/76.png',
                'category_id' => 3,
                "sub_id" => 1,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 77,
                'name' => 'スプラチャージャーベッチュー',
                'image_url' => '/weapon/77.png',
                'category_id' => 3,
                "sub_id" => 10,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 78,
                'name' => 'スプラスコープベッチュー',
                'image_url' => '/weapon/78.png',
                'category_id' => 3,
                "sub_id" => 10,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 79,
                'name' => 'リッター4K',
                'image_url' => '/weapon/79.png',
                'category_id' => 3,
                "sub_id" => 12,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 80,
                'name' => '4Kスコープ',
                'image_url' => '/weapon/80.png',
                'category_id' => 3,
                "sub_id" => 12,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 81,
                'name' => 'リッター4kカスタム',
                'image_url' => '/weapon/81.png',
                'category_id' => 3,
                "sub_id" => 9,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 82,
                'name' => '4kスコープカスタム',
                'image_url' => '/weapon/82.png',
                'category_id' => 3,
                "sub_id" => 9,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 83,
                'name' => 'ソイチューバー',
                'image_url' => '/weapon/83.png',
                'category_id' => 3,
                "sub_id" => 6,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 84,
                'name' => 'ソイチューバーカスタム',
                'image_url' => '/weapon/84.png',
                'category_id' => 3,
                "sub_id" => 8,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 85,
                'name' => 'スクイックリンα',
                'image_url' => '/weapon/85.png',
                'category_id' => 3,
                "sub_id" => 2,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 86,
                'name' => 'スクイックリンβ',
                'image_url' => '/weapon/86.png',
                'category_id' => 3,
                "sub_id" => 5,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 87,
                'name' => 'スクイックリンγ',
                'image_url' => '/weapon/87.png',
                'category_id' => 3,
                "sub_id" => 6,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 88,
                'name' => '14式竹筒銃・甲',
                'image_url' => '/weapon/88.png',
                'category_id' => 3,
                "sub_id" => 8,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 89,
                'name' => '14式竹筒銃・乙',
                'image_url' => '/weapon/89.png',
                'category_id' => 3,
                "sub_id" => 4,
                "special_id" => 14,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 90,
                'name' => '14式竹筒銃・丙',
                'image_url' => '/weapon/90.png',
                'category_id' => 3,
                "sub_id" => 13,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 91,
                'name' => 'バケットスロッシャー',
                'image_url' => '/weapon/91.png',
                'category_id' => 7,
                "sub_id" => 6,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 92,
                'name' => 'ヒーロースロッシャーレプリカ',
                'image_url' => '/weapon/92.png',
                'category_id' => 7,
                "sub_id" => 6,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 93,
                'name' => 'バケットスロッシャーデコ',
                'image_url' => '/weapon/93.png',
                'category_id' => 7,
                "sub_id" => 10,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 94,
                'name' => 'バケットスロッシャーソーダ',
                'image_url' => '/weapon/94.png',
                'category_id' => 7,
                "sub_id" => 1,
                "special_id" => 14,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 95,
                'name' => 'ヒッセン',
                'image_url' => '/weapon/95.png',
                'category_id' => 7,
                "sub_id" => 7,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 96,
                'name' => 'ヒッセン・ヒュー',
                'image_url' => '/weapon/96.png',
                'category_id' => 7,
                "sub_id" => 1,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 97,
                'name' => 'スクリュースロッシャー',
                'image_url' => '/weapon/97.png',
                'category_id' => 7,
                "sub_id" => 5,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 98,
                'name' => 'スクリュースロッシャーネオ',
                'image_url' => '/weapon/98.png',
                'category_id' => 7,
                "sub_id" => 2,
                "special_id" => 15,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 99,
                'name' => 'スクリュースロッシャーベッチュー',
                'image_url' => '/weapon/99.png',
                'category_id' => 7,
                "sub_id" => 13,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 100,
                'name' => 'エクスプロッシャー',
                'image_url' => '/weapon/100.png',
                'category_id' => 7,
                "sub_id" => 10,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 101,
                'name' => 'エクスプロッシャーカスタム',
                'image_url' => '/weapon/101.png',
                'category_id' => 7,
                "sub_id" => 2,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 102,
                'name' => 'オーバーフロッシャー',
                'image_url' => '/weapon/102.png',
                'category_id' => 7,
                "sub_id" => 3,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 103,
                'name' => 'オーバーフロッシャーデコ',
                'image_url' => '/weapon/103.png',
                'category_id' => 7,
                "sub_id" => 10,
                "special_id" => 7,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 104,
                'name' => 'バレルスピナー',
                'image_url' => '/weapon/104.png',
                'category_id' => 8,
                "sub_id" => 10,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 105,
                'name' => 'ヒーロースピナーレプリカ',
                'image_url' => '/weapon/105.png',
                'category_id' => 8,
                "sub_id" => 10,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 106,
                'name' => 'バレルスピナーデコ',
                'image_url' => '/weapon/106.png',
                'category_id' => 8,
                "sub_id" => 3,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 107,
                'name' => 'バレルスピナーリミックス',
                'image_url' => '/weapon/107.png',
                'category_id' => 8,
                "sub_id" => 2,
                "special_id" => 12,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 108,
                'name' => 'スプラスピナー',
                'image_url' => '/weapon/108.png',
                'category_id' => 8,
                "sub_id" => 7,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 109,
                'name' => 'スプラスピナーコラボ',
                'image_url' => '/weapon/109.png',
                'category_id' => 8,
                "sub_id" => 8,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 110,
                'name' => 'スプラスピナーベッチュー',
                'image_url' => '/weapon/110.png',
                'category_id' => 8,
                "sub_id" => 4,
                "special_id" => 11,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 111,
                'name' => 'ハイドラント',
                'image_url' => '/weapon/111.png',
                'category_id' => 8,
                "sub_id" => 5,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 112,
                'name' => 'ハイドラントカスタム',
                'image_url' => '/weapon/112.png',
                'category_id' => 8,
                "sub_id" => 12,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 113,
                'name' => 'クーゲルシュライバー',
                'image_url' => '/weapon/113.png',
                'category_id' => 8,
                "sub_id" => 4,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 114,
                'name' => 'クーゲルシュライバー・ヒュー',
                'image_url' => '/weapon/114.png',
                'category_id' => 8,
                "sub_id" => 9,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 115,
                'name' => 'ノーチラス47',
                'image_url' => '/weapon/115.png',
                'category_id' => 8,
                "sub_id" => 2,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 116,
                'name' => 'ノーチラス79',
                'image_url' => '/weapon/116.png',
                'category_id' => 8,
                "sub_id" => 6,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 117,
                'name' => 'スプラマニューバー',
                'image_url' => '/weapon/117.png',
                'category_id' => 2,
                "sub_id" => 7,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 118,
                'name' => 'スプラマニューバーコラボ',
                'image_url' => '/weapon/118.png',
                'category_id' => 2,
                "sub_id" => 8,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 119,
                'name' => 'ヒーローマニューバーレプリカ',
                'image_url' => '/weapon/119.png',
                'category_id' => 2,
                "sub_id" => 7,
                "special_id" => 5 ,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 120,
                'name' => 'スプラマニューバーベッチュー',
                'image_url' => '/weapon/120.png',
                'category_id' => 2,
                "sub_id" => 6,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 121,
                'name' => 'スパッタリー',
                'image_url' => '/weapon/121.png',
                'category_id' => 2,
                "sub_id" => 9,
                "special_id" => 7,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 122,
                'name' => 'スパッタリー・ヒュー',
                'image_url' => '/weapon/122.png',
                'category_id' => 2,
                "sub_id" => 4,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 123,
                'name' => 'スパッタリークリア',
                'image_url' => '/weapon/123.png',
                'category_id' => 2,
                "sub_id" => 11,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 124,
                'name' => 'デュアルスイーパー',
                'image_url' => '/weapon/124.png',
                'category_id' => 2,
                "sub_id" => 2,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 125,
                'name' => 'デュアルスイーパーカスタム',
                'image_url' => '/weapon/125.png',
                'category_id' => 2,
                "sub_id" => 1,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 126,
                'name' => 'ケルビン525',
                'image_url' => '/weapon/126.png',
                'category_id' => 2,
                "sub_id" => 12,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 127,
                'name' => 'ケルビン525デコ',
                'image_url' => '/weapon/127.png',
                'category_id' => 2,
                "sub_id" => 3,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 128,
                'name' => 'ケルビン525ベッチュー',
                'image_url' => '/weapon/128.png',
                'category_id' => 2,
                "sub_id" => 13,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 129,
                'name' => 'クアッドホッパーブラック',
                'image_url' => '/weapon/129.png',
                'category_id' => 2,
                "sub_id" => 5,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 130,
                'name' => 'クアッドホッパーホワイト',
                'image_url' => '/weapon/130.png',
                'category_id' => 2,
                "sub_id" => 10,
                "special_id" => 13,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 131,
                'name' => 'パラシェルター',
                'image_url' => '/weapon/131.png',
                'category_id' => 9,
                "sub_id" => 10,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 132,
                'name' => 'ヒーローシェルターレプリカ',
                'image_url' => '/weapon/132.png',
                'category_id' => 9,
                "sub_id" => 10,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 133,
                'name' => 'パラシェルターソレーラ',
                'image_url' => '/weapon/133.png',
                'category_id' => 9,
                "sub_id" => 5,
                "special_id" => 15,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 134,
                'name' => 'キャンピングシェルター',
                'image_url' => '/weapon/134.png',
                'category_id' => 9,
                "sub_id" => 9,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 135,
                'name' => 'キャンピングシェルターソレーラ',
                'image_url' => '/weapon/135.png',
                'category_id' => 9,
                "sub_id" => 3,
                "special_id" => 10,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 136,
                'name' => 'キャンピングシェルターカーモ',
                'image_url' => '/weapon/136.png',
                'category_id' => 9,
                "sub_id" => 12,
                "special_id" => 11,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 137,
                'name' => 'スパイガジェット',
                'image_url' => '/weapon/137.png',
                'category_id' => 9,
                "sub_id" => 12,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 138,
                'name' => 'スパイガジェットソレーラ',
                'image_url' => '/weapon/138.png',
                'category_id' => 9,
                "sub_id" => 1,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 139,
                'name' => 'スパイガジェットベッチュー',
                'image_url' => '/weapon/139.png',
                'category_id' => 9,
                "sub_id" => 11,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 140,
                'name' => '未選択',
                'image_url' => '/weapon/140.png',
                'category_id' => 10,
                "sub_id" => 0,
                "special_id" => 0,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 141,
                'name' => '講座系',
                'image_url' => '/weapon/141.jpg',
                'category_id' => 10,
                "sub_id" => 0,
                "special_id" => 0,
                "updated_at" => now(),
                "created_at" => now(),
            ],
        ];

        DB::table('m_weapons')->insert($data);
    }
}
