<?php

use Illuminate\Database\Seeder;

class WeaponsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => 1,
                'name' => 'スプラシューターコラボ',
                'category_id' => 1,
                "sub_id" => 1,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 2,
                'name' => '.52ガロン',
                'category_id' => 1,
                "sub_id" => 2,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 3,
                'name' => 'わかばシューター',
                'category_id' => 1,
                "sub_id" => 1,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 4,
                'name' => 'オクタシューターレプリカ',
                'category_id' => 1,
                "sub_id" => 1,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 5,
                'name' => '.96ガロンデコ',
                'category_id' => 1,
                "sub_id" => 3,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 6,
                'name' => 'シャープマーカー',
                'category_id' => 1,
                "sub_id" => 4,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 7,
                'name' => 'N-ZAP89',
                'category_id' => 1,
                "sub_id" => 5,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 8,
                'name' => 'N-ZAP85',
                'category_id' => 1,
                "sub_id" => 6,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 9,
                'name' => 'プライムシューター',
                'category_id' => 1,
                "sub_id" => 2,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 10,
                'name' => 'シャープマーカーネオ',
                'category_id' => 1,
                "sub_id" => 7,
                "special_id" => 7,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 11,
                'name' => 'ボールドマーカー',
                'category_id' => 1,
                "sub_id" => 8,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 12,
                'name' => 'ボールドマーカーネオ',
                'category_id' => 1,
                "sub_id" => 9,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 13,
                'name' => 'プロモデラーRG',
                'category_id' => 1,
                "sub_id" => 10,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 14,
                'name' => 'スプラシューター',
                'category_id' => 1,
                "sub_id" => 7,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 15,
                'name' => 'ボールドマーカーネオ',
                'category_id' => 1,
                "sub_id" => 9,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 16,
                'name' => '.52ガロンデコ',
                'category_id' => 1,
                "sub_id" => 8,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 17,
                'name' => 'L3リールガンD',
                'category_id' => 1,
                "sub_id" => 7,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 18,
                'name' => 'ジェットスイーパーカスタム',
                'category_id' => 1,
                "sub_id" => 7,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 19,
                'name' => 'プライムシューターコラボ',
                'category_id' => 1,
                "sub_id" => 6,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 20,
                'name' => 'もみじシューター',
                'category_id' => 1,
                "sub_id" => 5,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 21,
                'name' => 'プロモデラーMG',
                'category_id' => 1,
                "sub_id" => 6,
                "special_id" => 10,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 22,
                'name' => 'H3リールガンチェリー',
                'category_id' => 1,
                "sub_id" => 3,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 23,
                'name' => '.96ガロン',
                'category_id' => 1,
                "sub_id" => 10,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 24,
                'name' => 'ボールドマーカー7',
                'category_id' => 1,
                "sub_id" => 1,
                "special_id" => 11,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 25,
                'name' => 'N-ZAP83',
                'category_id' => 1,
                "sub_id" => 10,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 26,
                'name' => 'ヒーローシューターレプリカ',
                'category_id' => 1,
                "sub_id" => 7,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 27,
                'name' => 'L3リールガン',
                'category_id' => 1,
                "sub_id" => 8,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 28,
                'name' => 'ジェットスイーパー',
                'category_id' => 1,
                "sub_id" => 4,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 29,
                'name' => 'H3リールガン',
                'category_id' => 1,
                "sub_id" => 2,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 30,
                'name' => 'プロモデラーPG',
                'category_id' => 1,
                "sub_id" => 7,
                "special_id" => 12,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 31,
                'name' => 'H3リールガンD',
                'category_id' => 1,
                "sub_id" => 6,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' =>32,
                'name' => 'ボトルガイザー',
                'category_id' => 1,
                "sub_id" => 3,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' =>33,
                'name' => 'ボトルガイザーフォイル',
                'category_id' => 1,
                "sub_id" => 1,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' =>34,
                'name' => 'スプラシューターベッチュー',
                'category_id' => 1,
                "sub_id" => 6,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' =>35,
                'name' => 'プライムシューターベッチュー',
                'category_id' => 1,
                "sub_id" => 1,
                "special_id" => 12,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' =>36,
                'name' => 'おちばシューター',
                'category_id' => 1,
                "sub_id" => 11,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' =>37,
                'name' => 'L3リールガンベッチュー',
                'category_id' => 1,
                "sub_id" => 3,
                "special_id" => 11,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' =>38,
                'name' => '.52ガロンベッチュー',
                'category_id' => 1,
                "sub_id" => 3,
                "special_id" => 12,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            //category2
            [
                'id' => 39,
                'name' => 'デュアルスイーパー',
                'category_id' => 2,
                "sub_id" => 2,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 40,
                'name' => 'デュアルスイーパーカスタム',
                'category_id' => 2,
                "sub_id" => 1,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 41,
                'name' => 'スプラマニューバー',
                'category_id' => 2,
                "sub_id" => 7,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 42,
                'name' => 'スプラマニューバーコラボ',
                'category_id' => 2,
                "sub_id" => 8,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 43,
                'name' => 'スパッタリー',
                'category_id' => 2,
                "sub_id" => 9,
                "special_id" => 7,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 44,
                'name' => 'ヒーローマニューバーレプリカ',
                'category_id' => 2,
                "sub_id" => 7,
                "special_id" => 5 ,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 45,
                'name' => 'ケルビン525',
                'category_id' => 2,
                "sub_id" => 12,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 46,
                'name' => 'スパッタリー・ヒュー',
                'category_id' => 2,
                "sub_id" => 4,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 47,
                'name' => 'クアッドホッパーブラック',
                'category_id' => 2,
                "sub_id" => 5,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 48,
                'name' => 'ケルビン525デコ',
                'category_id' => 2,
                "sub_id" => 3,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 49,
                'name' => 'クアッドホッパーホワイト',
                'category_id' => 2,
                "sub_id" => 10,
                "special_id" => 13,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 50,
                'name' => 'スプラマニューバーベッチュー',
                'category_id' => 2,
                "sub_id" => 6,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 51,
                'name' => 'ケルビン525ベッチュー',
                'category_id' => 2,
                "sub_id" => 13,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 52,
                'name' => 'スパッタリークリア',
                'category_id' => 2,
                "sub_id" => 3,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            //チャージャー３
            [
                'id' => 53,
                'name' => 'スプラスコープ',
                'category_id' => 3,
                "sub_id" => 1,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 54,
                'name' => 'スクイックリンα',
                'category_id' => 3,
                "sub_id" => 2,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 55,
                'name' => 'スプラチャージャー',
                'category_id' => 3,
                "sub_id" => 1,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 56,
                'name' => '14式竹筒銃・甲',
                'category_id' => 3,
                "sub_id" => 8,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 57,
                'name' => 'ヒーローチャージャーレプリカ',
                'category_id' => 3,
                "sub_id" => 1,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 58,
                'name' => 'スクイックリンγ',
                'category_id' => 3,
                "sub_id" => 6,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 59,
                'name' => '14式竹筒銃・丙',
                'category_id' => 3,
                "sub_id" => 13,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 60,
                'name' => 'スクイックリンβ',
                'category_id' => 3,
                "sub_id" => 5,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 61,
                'name' => '14式竹筒銃・乙',
                'category_id' => 3,
                "sub_id" => 4,
                "special_id" => 14,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 62,
                'name' => 'ソイチューバー',
                'category_id' => 3,
                "sub_id" => 6,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 63,
                'name' => 'スプラチャージャー コラボ',
                'category_id' => 3,
                "sub_id" => 3,
                "special_id" => 7,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 64,
                'name' => 'スプラスコープ コラボ',
                'category_id' => 3,
                "sub_id" => 3,
                "special_id" => 7,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 65,
                'name' => 'リッター4K',
                'category_id' => 3,
                "sub_id" => 12,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 66,
                'name' => '4Kスコープ',
                'category_id' => 3,
                "sub_id" => 12,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 67,
                'name' => 'リッター4kカスタム',
                'category_id' => 3,
                "sub_id" => 9,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 68,
                'name' => '4kスコープカスタム',
                'category_id' => 3,
                "sub_id" => 9,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 69,
                'name' => 'ソイチューバーカスタム',
                'category_id' => 3,
                "sub_id" => 8,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 70,
                'name' => 'スプラチャージャーベッチュー',
                'category_id' => 3,
                "sub_id" => 10,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 71,
                'name' => 'スプラスコープベッチュー',
                'category_id' => 3,
                "sub_id" => 10,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            //ブラスター４
            [
                'id' => 72,
                'name' => 'ノヴァブラスターネオ',
                'category_id' => 4,
                "sub_id" => 12,
                "special_id" => 7,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 73,
                'name' => 'ロングブラスターカスタム',
                'category_id' => 4,
                "sub_id" => 8,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 74,
                'name' => 'ホットブラスターカスタム',
                'category_id' => 4,
                "sub_id" => 5,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 75,
                'name' => 'ノヴァブラスター',
                'category_id' => 4,
                "sub_id" => 1,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 76,
                'name' => 'ラピッドブラスター',
                'category_id' => 4,
                "sub_id" => 12,
                "special_id" => 15,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 77,
                'name' => 'ロングブラスターネクロ',
                'category_id' => 4,
                "sub_id" => 7,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 78,
                'name' => 'ホットブラスター',
                'category_id' => 4,
                "sub_id" => 4,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 79,
                'name' => 'Rブラスターエリートデコ',
                'category_id' => 4,
                "sub_id" => 3,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 80,
                'name' => 'Rブラスターエリート',
                'category_id' => 4,
                "sub_id" => 4,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 81,
                'name' => 'ラピッドブラスターデコ',
                'category_id' => 4,
                "sub_id" => 6,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 82,
                'name' => 'ロングブラスター',
                'category_id' => 4,
                "sub_id" => 6,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 83,
                'name' => 'クラッシュブラスター',
                'category_id' => 4,
                "sub_id" => 1,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 84,
                'name' => 'ヒーローブラスターレプリカ',
                'category_id' => 4,
                "sub_id" => 4,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 85,
                'name' => 'クラッシュブラスターネオ',
                'category_id' => 4,
                "sub_id" => 8,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 86,
                'name' => 'ノヴァブラスターベッチュー',
                'category_id' => 4,
                "sub_id" => 13,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 87,
                'name' => 'ラピッドブラスターベッチュー',
                'category_id' => 4,
                "sub_id" => 11,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            //ローラー５
            [
                'id' => 88,
                'name' => 'ダイナモローラー',
                'category_id' => 5,
                "sub_id" => 12,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 89,
                'name' => 'スプラローラーコラボ',
                'category_id' => 5,
                "sub_id" => 9,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 90,
                'name' => 'カーボンローラー',
                'category_id' => 5,
                "sub_id" => 5,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 91,
                'name' => 'ダイナモローラーテスラ',
                'category_id' => 5,
                "sub_id" => 1,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 92,
                'name' => 'スプラローラー',
                'category_id' => 5,
                "sub_id" => 8,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 93,
                'name' => 'カーボンローラーデコ',
                'category_id' => 5,
                "sub_id" => 7,
                "special_id" => 13,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 94,
                'name' => 'ヒーローローラーレプリカ',
                'category_id' => 5,
                "sub_id" => 8,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 95,
                'name' => 'ヴァリアブルローラー',
                'category_id' => 5,
                "sub_id" => 3,
                "special_id" => 15,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 96,
                'name' => 'ヴァリアブルローラーフォイル',
                'category_id' => 5,
                "sub_id" => 6,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 97,
                'name' => 'スプラローラーベッチュー',
                'category_id' => 5,
                "sub_id" => 1,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 98,
                'name' => 'ダイナモローラーベッチュー',
                'category_id' => 5,
                "sub_id" => 10,
                "special_id" => 12,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            //フデ６
            [
                'id' => 99,
                'name' => 'ホクサイ',
                'category_id' => 6,
                "sub_id" => 5,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 100,
                'name' => 'パブロ',
                'category_id' => 6,
                "sub_id" => 1,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 101,
                'name' => 'ホクサイ・ヒュー',
                'category_id' => 6,
                "sub_id" => 9,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 102,
                'name' => 'パーマネント・パブロ',
                'category_id' => 6,
                "sub_id" => 10,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 103,
                'name' => 'パブロ・ヒュー',
                'category_id' => 6,
                "sub_id" => 12,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 104,
                'name' => 'ヒーローブラシレプリカ',
                'category_id' => 6,
                "sub_id" => 5,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 105,
                'name' => 'ホクサイベッチュー',
                'category_id' => 6,
                "sub_id" => 6,
                "special_id" => 11,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            //スロッシャー7
            [
                'id' => 106,
                'name' => 'バケットスロッシャー',
                'category_id' => 7,
                "sub_id" => 6,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 107,
                'name' => 'ヒッセン',
                'category_id' => 7,
                "sub_id" => 7,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 108,
                'name' => 'スクリュースロッシャー',
                'category_id' => 7,
                "sub_id" => 5,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 109,
                'name' => 'バケットスロッシャーデコ',
                'category_id' => 7,
                "sub_id" => 10,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 110,
                'name' => 'バケットスロッシャーソーダ',
                'category_id' => 7,
                "sub_id" => 1,
                "special_id" => 14,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 111,
                'name' => 'ヒッセン・ヒュー',
                'category_id' => 7,
                "sub_id" => 1,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 112,
                'name' => 'スクリュースロッシャーネオ',
                'category_id' => 7,
                "sub_id" => 2,
                "special_id" => 15,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 113,
                'name' => 'ヒーロースロッシャーレプリカ',
                'category_id' => 7,
                "sub_id" => 6,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 114,
                'name' => 'エクスプロッシャー',
                'category_id' => 7,
                "sub_id" => 10,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 115,
                'name' => 'オーバーフロッシャー',
                'category_id' => 7,
                "sub_id" => 3,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 116,
                'name' => 'スクリュースロッシャーベッチュー',
                'category_id' => 7,
                "sub_id" => 13,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 117,
                'name' => 'エクスプロッシャーカスタム',
                'category_id' => 7,
                "sub_id" => 2,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 118,
                'name' => 'オーバーフロッシャーデコ',
                'category_id' => 7,
                "sub_id" => 10,
                "special_id" => 7,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            //スピナー８
            [
                'id' => 119,
                'name' => 'スプラスピナーコラボ',
                'category_id' => 8,
                "sub_id" => 8,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 120,
                'name' => 'バレルスピナーデコ',
                'category_id' => 8,
                "sub_id" => 3,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 121,
                'name' => 'ハイドラントカスタム',
                'category_id' => 8,
                "sub_id" => 12,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 122,
                'name' => 'バレルスピナー',
                'category_id' => 8,
                "sub_id" => 10,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 123,
                'name' => 'バレルスピナーリミックス',
                'category_id' => 8,
                "sub_id" => 2,
                "special_id" => 12,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 124,
                'name' => 'ハイドラント',
                'category_id' => 8,
                "sub_id" => 5,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 125,
                'name' => 'スプラスピナー',
                'category_id' => 8,
                "sub_id" => 7,
                "special_id" => 5,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 126,
                'name' => 'ヒーロースピナーレプリカ',
                'category_id' => 8,
                "sub_id" => 10,
                "special_id" => 8,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 127,
                'name' => 'クーゲルシュライバー',
                'category_id' => 8,
                "sub_id" => 4,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 128,
                'name' => 'ノーチラス47',
                'category_id' => 8,
                "sub_id" => 2,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 129,
                'name' => 'クーゲルシュライバー・ヒュー',
                'category_id' => 8,
                "sub_id" => 9,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 130,
                'name' => 'ノーチラス79',
                'category_id' => 8,
                "sub_id" => 6,
                "special_id" => 1,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 131,
                'name' => 'スプラスピナーベッチュー',
                'category_id' => 8,
                "sub_id" => 4,
                "special_id" => 11,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            //シェルター９
            [
                'id' => 132,
                'name' => 'パラシェルター',
                'category_id' => 9,
                "sub_id" => 10,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 133,
                'name' => 'ヒーローシェルターレプリカ',
                'category_id' => 9,
                "sub_id" => 10,
                "special_id" => 6,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 134,
                'name' => 'キャンピングシェルター',
                'category_id' => 9,
                "sub_id" => 9,
                "special_id" => 9,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 135,
                'name' => 'スパイガジェット',
                'category_id' => 9,
                "sub_id" => 12,
                "special_id" => 4,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 136,
                'name' => 'パラシェルターソレーラ',
                'category_id' => 9,
                "sub_id" => 5,
                "special_id" => 15,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 137,
                'name' => 'スパイガジェットソレーラ',
                'category_id' => 9,
                "sub_id" => 1,
                "special_id" => 2,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 138,
                'name' => 'キャンピングシェルターソレーラ',
                'category_id' => 9,
                "sub_id" => 3,
                "special_id" => 10,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 139,
                'name' => 'スパイガジェットベッチュー',
                'category_id' => 9,
                "sub_id" => 11,
                "special_id" => 3,
                "updated_at" => now(),
                "created_at" => now(),
            ],
            [
                'id' => 140,
                'name' => 'キャンピングシェルターカーモ',
                'category_id' => 9,
                "sub_id" => 12,
                "special_id" => 11,
                "updated_at" => now(),
                "created_at" => now(),
            ],
        ];

        DB::table('m_weapons')->insert($data);
    }
}
